<?
$PERM["search"]["8"]="W";
$PERM["search"]["5"]="W";
$PERM["login"]["8"]="W";
$PERM["obyavleniya"]["8"]="W";
$PERM["o-servise"]["8"]="W";
$PERM["glavnaya-stranitsa"]["8"]="W";
$PERM["lichnyy-kabinet-pokupatelya"]["*"]="D";
$PERM["lichnyy-kabinet-pokupatelya"]["G1"]="X";
$PERM["lichnyy-kabinet-pokupatelya"]["G6"]="W";
$PERM["lichnyy-kabinet-prodavtsa"]["*"]="D";
$PERM["lichnyy-kabinet-prodavtsa"]["G1"]="X";
$PERM["lichnyy-kabinet-prodavtsa"]["G7"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
$PERM["index.php"]["5"]="W";
$PERM["/"]["*"]="R";
?>